### ISSUE TITLE
Freeze or Crash (intel / compositing): after some time, whole desktop may freeze or crash (tty2 still works)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#1]
References:
https://bugs.launchpad.net/kubuntu-ppa/+bug/1384512

bugs.kde.org:
https://bugs.kde.org/show_bug.cgi?id=338999
https://bugs.kde.org/show_bug.cgi?id=338999#c23 (seems to happen with oxygen too)
https://bugs.kde.org/show_bug.cgi?id=338999#c33 (seems to happen with fast video output)

https://bugs.kde.org/show_bug.cgi?id=340876#c11 (Qt5.4 experience)
https://bugs.kde.org/show_bug.cgi?id=340876#c23 (glamor settings)
http://www.reddit.com/r/archlinux/comments/2khbci/kde_5_for_the_regular_arch_kde_4_user/cllsk2h

**Comment by star-buck** [comment]
desktop still freezing, but not crashing anymore.
It is doing so under GL and with Breeze theme, so its not aurorae causing this.
Missing shadows even with Xrender, so I would also tend to say its shadows-related?

**Comment by mgraesslin** [comment]
> desktop still freezing, but not crashing anymore.

quite bad. Will have to try whether I hit it on the notebook.

> Missing shadows even with Xrender, so I would also tend to say its shadows-related?

no, that just means shadows on Xrender are broken

**Comment by star-buck** [comment]
tried with varios intel gfx now, here is latest freezing:
VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)

**Comment by star-buck** [comment]
while using xrender, window deco sometimes also looks like this:
![xrender](https://cloud.githubusercontent.com/assets/840070/5692635/f2ed31ee-98fd-11e4-8c65-98f36b5d178d.png)

**Comment by mgraesslin** [comment]
the xrender decoration is completely unrelated and a different issue -> new bug report?

**Comment by mgraesslin** [comment]
Concerning the freeze: I just installed Qt 5.4 on my notebook and are able to reproduce the problem there. I have created a patch which disables the new feature (https://git.reviewboard.kde.org/r/122008/ ) which "fixes" the freezes for me.

**Comment by mgraesslin** [comment]
xrender shadow reported as https://bugs.kde.org/show_bug.cgi?id=342758

**Comment by mgraesslin** [comment]
The freeze has now been hotfixed by requiring an environment variable to be set to enable the feature. Several developers expressed the opinion that in master the feature should be enabled to get better testing. As the maintainer I'm not going to veto this. But it would mean that the isos being build from master would break again.

**Comment by star-buck** [comment]
how can i set that variable to disabled in latest KCI 20150116?

**Comment by davidedmundson** [comment]
It is disabled by default.
i.e you shouldn't see freezes now.

**Comment by star-buck** [comment]
Since it still freezes, is there any way to check the config or see if it
is packaged right in kci?

**Comment by mgraesslin** [comment]
this might mean that there is yet another Intel related problem :-(

* When do you experience that freeze?
* Is there anything you do, which triggers the freeze?
* Did you change any compositing related settings?

If the freeze does not happen directly on startup I might be able to give you a few combination of settings to test through so that we can narrow down the problem.

**Comment by star-buck** [comment]
It happens after doing some things for a while, for example scrolling fast
on firefox...
But i would like to know how can I verify that the config patch is
installed (what package) and if installed on the latest kci, set correctly?
I would appreciate if we make those two verification processes (just to
rule out any failure of those two) always transparent.

**Comment by davidedmundson** [comment]
My usual approach is

apt-cache policy "name of package".

The name of the package can be a bit of guesswork; sometimes I use apt-cache search to find it.

that will say something like:

kwin:
  Installed: 4:5.1.2+git20150108.1327+14.10-0ubuntu0

the format is

randomnumber : last formal release + "git" then the date that snapshot was made 
followed by + and then some garbarge again.

the date the git snapshot was taken is the important bit. In this case
20150108.1327

I then typically cross reference it against the git commit log for that file or when people comment in the github issues.

**Comment by star-buck** [comment]
So 20150108 likely is still not patched and configured yet (since kci from
last week 20150109 also freezed)?
If it would be installed, is there any way to configure it, since it was
meant to be on default, but could be turned off?

**Comment by davidedmundson** [comment]
Edit: I've confused myself.

The latest ISO has changed the repository used.

It used to be http://ppa.launchpad.net/kubuntu-ci/unstable-daily/
now it's http://ppa.launchpad.net/kubuntu-ci/stable-daily/

which does have a newer version of kwin. So stable is newer than unstable?

However, I can't install the new ISO due to some installer issue, so I took my install from last week and upgraded it; however that has no effect because the repos changed.

**Comment by star-buck** [comment]
But you could add the new repo and simply update to check patch and
function? Again, is there any way to check the patched version itself
(sorry for repeating myself)??

**Comment by davidedmundson** [comment]
the feature which is broken, is off by default

you can use KWIN_USE_INTEL_SWAP_EVENT=1 kwin_x11 --replace to turn it on, but that will just go back to the completely frozen situation we had over christmas so it's probably not a good idea.

**Comment by star-buck** [comment]
after 2+ hour of testing, this seems to behave stable now :) I am setting this to green, but leave it open for some more time while testing...

**Comment by star-buck** [comment]
whole day stable, so closing this for good :)
