### ISSUE TITLE
hardware power button: nothing happens, does not show power options

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#33]

**Comment by star-buck** [comment]
still not working as of kci 20150109
any update on this?

**Comment by star-buck** [comment]
not working on kci20150116, any update?

**Comment by star-buck** [comment]
@sebasje : will you fix this or someone else should be assigned?

**Comment by sebasje** [comment]
This works for me on kci20150116.

While I don't think it could be a hardware thing (the powerbutton handling is I think pretty standard), what hardware are you testing it on? (Lenovo 540M here).

Could you run "xev" in a console, wait a bit until all events have been printed, and then hit the powerbutton? What does this return?

**Comment by star-buck** [comment]
xev shows nothing when pressing power button.
so this still doesnt work here in kci20150123.

**Comment by sebasje** [comment]
What hardware is that?

**Comment by mgraesslin** [comment]
if xev doesn't show en event it quite certainly meanst that the button isn't supported by the operating system. Does it work on other distributions (e.g. different kernel version)?

**Comment by star-buck** [comment]
@sebas: acer spire, asus pc both not working, i could test more, but it surely was working on those two with all previous kde4.x versions.

**Comment by davidedmundson** [comment]
Found it.

Commit a34affeb in powerdevil by Alex replaces 

HandleButtonEvents::isSupported() 
from checking if we have any hardware buttons to checking if we have a lid.

If you're on a desktop this completely is not even remotely close to the same thing.

Patch incoming.

**Comment by davidedmundson** [comment]
https://git.reviewboard.kde.org/r/122387/

**Comment by davidedmundson** [comment]
Merged

**Comment by apachelogger** [comment]
please remember to post the commit ref in the future :wink:

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4752088/+listing-archive-extra

**Comment by star-buck** [comment]
the great thing: it works, so power button invokes a reaction!
Now still a popup wants me to confirm logout or shutdown (whatever is set as preferred option under "Startip & Shutdown"), where in kde4.x i was able to simply shut it down immediately.
Any way to shut down right away without the 30 seconds confirmation dialog?

**Comment by davidedmundson** [comment]
systemsettings -> power management -> button event handling select -> when power button pressed: 
select shutdown

This was is in the 5.2 branch, but not in 5.2.0

It's in the kubuntu-CI packaging, but I don't know if it's in netrunner yet.
 commit a17b7791c9f98d76da35b81649650cc8a20974fd if you're cherry-picking things

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4759387/+listing-archive-extra

**Comment by star-buck** [comment]
works.
