### ISSUE TITLE
[window decoration kcm]: shows black area where window decos should be

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#45]

**Comment by davidedmundson** [comment]
This is one of the things that should hopefully have been fixed with Qt5.4. I just opened it 5 times in a row and it worked each time for me.

Qt5.4 came in on the 19th December so one week after this was reported, so there's a very good chance this is closable.

**Comment by mgraesslin** [comment]
https://bugs.kde.org/show_bug.cgi?id=341971

The bug report is from Jan who I know from other bugs to be running a Qt 5.4 setup.

**Comment by star-buck** [comment]
still happeneing with kci 20150116

**Comment by star-buck** [comment]
also reported here: https://forum.manjaro.org/index.php?topic=18150.msg178192#msg178192

**Comment by eikehein** [comment]
I'm guessing this is the usual problem with embedding Qt Quick stuff in System Settings. Marco did some work on investigating this about half a year ago I think, and on alternate approaches (going back to XEmbed, etc.). He should know the status of this upstream in Qt.

**Comment by notmart** [comment]
i don't think QQuickWidget is being fixed anytime soon in Qt, for what i understood is an architectural problem that may be not solvable. basically as soon anybody, anywhere in the process calls winId() of the window of the qquickwidget, it will instantly break and become black.
unfortunaly, i think the only way is to do like the other kcms, and go back to Xembed

**Comment by star-buck** [comment]
but it wasnt always crashing, so did we change from Xemebed recently and can reverse/downgrade, since crashing is the worst option from a users persepctive?

**Comment by mgraesslin** [comment]
issue fixed - http://commits.kde.org/kwin/63885cc5b3f2922441dac0af96ed001b737e78ea
fixed date: 28.01.
package: kwin
target iso: next

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4694466/+listing-archive-extra

**Comment by star-buck** [comment]
seems fixed
