### ISSUE TITLE
kdeco2: option to select button size

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#50]
would be great to have that feature back

**Comment by mgraesslin** [comment]
button size only existed in Aurorae SVG themes. I'm quite unsure whether this is needed. The buttons should already scale with the title font. Do you have a specific use case for buttons which do not scale with the title?

**Comment by mgraesslin** [comment]
I just pushed a commit to bring back button size configuration in Aurorae: http://commits.kde.org/kwin/c565017720072bfbba6816a5a0b75efdbd313e79

This change will not be in 5.2 as we are in string freeze.

**Comment by mgraesslin** [comment]
package: kwin
fixed: Wed, 14th
target ISO: unknown, next build on master

**Comment by star-buck** [comment]
this needs netrunner ppa packaging, as its not part of official 5.2.

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4694466/+listing-archive-extra

**Comment by star-buck** [comment]
works
