### ISSUE TITLE
ksnapshot: taking a snapshot has sometimes the opened file dialog window where to save the file added to the screenshot afterwards

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#52]
sounds like timewarp magic has been added to frameworks lately...

**Comment by star-buck** [comment]
Example (not Photoshopped!!! only removed the annoying "e" in jpeg per hand):
![ksnapshot](https://cloud.githubusercontent.com/assets/840070/5743741/7a3648d2-9c1b-11e4-8fbd-6c586f5722ab.jpg)

**Comment by eikehein** [comment]
^ It's worth noting that this is the KDE 4 version of KSnapshot (you can tell by the position of the buttons in the Save As dialog - the KF5 dialog uses QDialogButtonBox and has the buttons at the bottom, which is ugly by the way). It's probably a real bug in the KDE 4 version, but I'm not sure if we're ever going to make a release of it again -- the next KDE Applications release should probably ship the KF5 port, where I can't reproduce this ...

**Comment by star-buck** [comment]
another weirdness:
PRINT brings up ksnapshot with its own popup overlaying the snapshot already (which it didnt do in kde4)

**Comment by eikehein** [comment]
^ Martin, I asked Clemens to try that qdbus command because my hunch is that there might be a delay due to the async screenshot taking via KWin. Unfortunately we didn't make progress though. What do you think about that angle?

(I currently can't reproduce this problem on the system installed from the ISO or on other systems.)

**Comment by star-buck** [comment]
just posted on IRC:
another angle i tried testing your kwin theory:
(10:31:19 PM) starbuck11: xrender instead of opengl solves this even with mouse cursor disabled!
(10:31:23 PM) starbuck11: hooray!
(10:32:18 PM) starbuck11: so thats why with netrunner over here constantly failing with opengl and intel and therefore setting to xrender default (as advised) was taking screenshots just fine

**Comment by star-buck** [comment]
https://www.dropbox.com/s/yo7fyv1y0zpceit/knsapshot.mkv?dl=0

**Comment by mgraesslin** [comment]
I'm able to reproduce the problem on my notebook with the current ISO.

**Comment by mgraesslin** [comment]
I did some testing yesterday and tried all possible combinations of repaint strategies and buffer handling in KWin with OpenGL compositing. The problem was present with all of them.

My current theory is that X reads from KWin's write buffer instead of the read buffer. If that's the case the problem should be reproducable with any OpenGL compositor.

**Comment by mgraesslin** [comment]
Not reproducable with Compton. This makes everything more confusable.

**Comment by mgraesslin** [comment]
Doesn't happen with EGL

**Comment by mgraesslin** [comment]
and I cannot reproduce on Debian.

**Comment by mgraesslin** [comment]
Maybe relevant packages:
* libdrm-intel1:
 * Debian testing: 2.4.58
 * Ubuntu utopic: 2.4.56
 * Ubuntu vivid: 2.4.58
* xserver-xorg-video-intel:
 * Debian testing: 2.21.15
 * Ubuntu utopic: 2.99.914
 * Ubuntu vivid: 2.99.917
* xserver-common:
 * Debian testing: 1.16.2
 * Ubuntu utopic: 1.16.0
 * Ubuntu vivid: 1.16.2
* libgl1-mesa-dri:
 * Debian testing: 10.3.2
 * Ubuntu utopic: 10.3.0
 * Ubuntu vivid: 10.3.2

Overall the ISO (based on utopic) has older versions than Debian testing. Especially bug fix releases are missing in X, mesa and drm. All of them are updated in vivid to the same version which is in Debian testing. Given that I suggest that we move back any further investigations till the ISO switched over to vivid.

Another possibility is that the xserver-xorg-video-intel is at fault here. Ubuntu is shipping an experimental package (notice the version number .99 and it's in Debian experimental with an explicit "exp" suffix in the package version). I could try to install that package on my system, but I'm hesitant as I fear to destroy the system by installing experimental drivers.

**Comment by mgraesslin** [comment]
I just tested the vivid live cd (still Plasma 5.1, though) and there the problem is not reproducable.

**Comment by mgraesslin** [comment]
and another test: Kubuntu 14.10 tech preview live iso shows the problem.

**Comment by star-buck** [comment]
yes, it is very likely xserver-xorg-video-intel:
I updated to 2.99.917 on utopic and ksnapshot became normal, so I would rule out the other packages.

You think it is safe to close this or might there be something on our side lurking, as the ksnapshot behaviour was certainly a bit frightening ;)

**Comment by mgraesslin** [comment]
Given the testing I did I'm 99.9 % sure that we are innocent here.

**Comment by star-buck** [comment]
okay, closing then here
