### ISSUE TITLE
Kicker: Menu closing with delay and without

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#53]
* if one category is open, the main menu closes first and then the opened category closes after a short delay
* if three panes are open though (another subcategory), all three close nearly instantly
https://www.dropbox.com/s/cu1buvn2g1i8mgg/kicker-closing-menu.mkv?dl=0

**Comment by star-buck** [comment]
Hitting ESC closes all open menu panes also at once.

**Comment by eikehein** [comment]
Fixed by http://quickgit.kde.org/?p=plasma-desktop.git&a=commit&h=adea1596d5482eddf9d615b173cbf58bc1f903d1

**Comment by eikehein** [comment]
package: plasma-desktop
fixed: Fri 16th
target ISO: Fri 23rd
qa method: disable the fade and slide effects, open kicker and a submenu, click on the desktop outside it - both dialogs should appear to close at the same time

**Comment by star-buck** [comment]
works!

**Comment by eikehein** [comment]
yay :)
