### ISSUE TITLE
[netrunner] qml look (example muon)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#58]
muon kci:
![moun-install-kci](https://cloud.githubusercontent.com/assets/840070/5854423/f116d756-a22d-11e4-92ea-be815767e6e9.png)
muon netrunner:
![muon-install-netrunner](https://cloud.githubusercontent.com/assets/840070/5854424/f118e23a-a22d-11e4-8fb6-0c01e45e75a4.png)
compare the missing style/format, like button and breadcrumbs

**Comment by aleixpol** [comment]
Are standard plasma themes installed?
Muon Discover used "default" theme, when using light color themes (referred to as Air, I believe).

**Comment by star-buck** [comment]
that was it, thanks!
