### ISSUE TITLE
[oxygen widget theme]: mouse hovering leaves menu entry visually selected

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#59]
seems to happen with oxygen widget style only, has not happened with breeze
see "Refresh Desktop" entry and "Lock widgets" selected visually:
![refresh-lag](https://cloud.githubusercontent.com/assets/840070/5863592/f2fbb1f2-a27a-11e4-91c8-d631c32e8152.png)
tested with kci20150116

**Comment by eikehein** [comment]
Yeah, this is a very old bug in Oxygen.

**Comment by star-buck** [comment]
any reference ticket?

i just tried here, since i never noticed that before and no matter what i do, i cannot reproduce thison my two machines still running kde4 with oxygen widget theme... where on plasma5 its almost impossible to not get this effect...?

**Comment by eikehein** [comment]
Here: https://bugs.kde.org/show_bug.cgi?id=332377

I've added a poke there now.

**Comment by star-buck** [comment]
no longer noticed as of recently
