### ISSUE TITLE
status summary

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#60]
KCMs:
touchpad: is todo and should be brought into KDE
kwalletmanager: frameworks branch is being worked on by lukas tinkl
kamera ioslave and kcm: needs a port
bluedevil: port is done I believe, needs a release
kdeconnect: port is done, needs a release
proxy: sho ported, needs review https://gerrit.vesnicky.cesnet.cz/r/200
removeable devices: todo
audiocd: todo
user-manager: vhanda did a port, alex needs to do release
kscreen: needs a release

copy&paste: https://github.com/blue-systems/plasma-5.2/issues/37
package: libqt5gui5
patched: Dec, 10th

dolphin bookmarks disappearing:
package:
patch:

click-eating: https://github.com/blue-systems/plasma-5.2/issues/29
package: libqt5gui5
patch: https://codereview.qt-project.org/#/c/104061/

add oxygen deco: https://github.com/blue-systems/plasma-5.2/issues/40
package: liboxygenstyle5-5 + probably a new package

oxygen shadows missing: https://github.com/blue-systems/plasma-5.2/issues/18
package: ?

kwin freeze:
package: kwin

aurorae shadows rendering:
package:

**Comment by davidedmundson** [comment]
> kscreen: needs a release
this has  a release within Plasma 5.2.

**Comment by davidedmundson** [comment]
Jonathan made a release of User Manager 

It was like a beta ready for Plasma 5.3, but it didn't go into the final 5.2.0 as it was all a bit late and it still duplicates some functionality.

It should be package-able for Netrunner
http://download.kde.org/unstable/plasma/5.1.95/user-manager-5.1.95.tar.xz
