### ISSUE TITLE
[kicker]: submenus not closed sometimes

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#64]
https://bugs.kde.org/show_bug.cgi?id=342703

**Comment by eikehein** [comment]
Are you still seeing this right now? (I still haven't been able to reproduce it anywhere and it's not been mentioned to me lately.)

**Comment by star-buck** [comment]
latest kci from firday still has this. 
It seems that turning off compositing completely has a higher success rate at randomly reproducing this.

**Comment by eikehein** [comment]
Ok, thanks for the update :)

**Comment by eikehein** [comment]
Should be fixed: https://commits.kde.org/plasma-desktop/4116dfbfa34dcb50259e6bdef7eb212a8690766f

Flying blind, though (I would never reproduce), so I would appreciate testing. The changes are QML-only and don't require compilation, so I can provide assistance with hotpatching an existing install for testing.

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4697944/+listing-archive-extra

**Comment by star-buck** [comment]
works
