### ISSUE TITLE
[plasma-volume-control]: when added to panel, crashes plasmashell continously

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#65]

**Comment by apachelogger** [comment]
@star-buck do you get a backtrace for this? also, with which combination of PPAs does this happen?

**Comment by star-buck** [comment]
the pulseaudio.desktop kcm file in "kservices5" folder comes installed with it?
i am asking because it seems not getting removed when uninstalling "plasma-volume-control" (its left over) and actually does freeze when clicked under system settings.

**Comment by apachelogger** [comment]
yes, it not getting removed seems just as odd as it crashing though

me@smith:~$ dpkg -S kcm_pulseaudio.desktop
plasma-volume-control: /usr/share/kservices5/kcm_pulseaudio.desktop

me@smith:~$ sudo dpkg --remove plasma-volume-control
(Reading database ... 668856 files and directories currently installed.)
Removing plasma-volume-control (0.0+git20141028+r99.3~ubuntu14.10.1) ...
Processing triggers for libc-bin (2.19-10ubuntu2.2) ...

me@smith:~$ dpkg -S kcm_pulseaudio.desktop
dpkg-query: no path found matching pattern *kcm_pulseaudio.desktop*

**Comment by star-buck** [comment]
attached usb camera apparently causes the crashes, 
needs fixing as it still happens with the latest update in blueshellnext.

**Comment by apachelogger** [comment]
I still need a backtrace created with the fixed dbg package.

**Comment by apachelogger** [comment]
this should fix the crash

https://code.launchpad.net/~blue-shell-next/+archive/ubuntu/builds/+sourcepub/4768267/+listing-archive-extra

**Comment by star-buck** [comment]
works!
