### ISSUE TITLE
[kate]: opening two text files at same time produces a temporary freeze

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#66]

**Comment by mck182** [comment]
This is a known issue and was already raised at kde-frameworks-devel by the kate author, so far there's no solution yet afaik.

For reference - https://www.marc.info/?l=kde-frameworks-devel&m=141042877830344&w=1

**Comment by star-buck** [comment]
since one often uses kate+dolphin to edit multiple documents at the same time, it should be a high priority to fix nevertheless

**Comment by mck182** [comment]
Yes, I don't say it shouldn't, I'm just pointing out that the Kate developers know about it and they were still unable to fix it properly.

I'll try to nudge them a bit.

**Comment by star-buck** [comment]
Thanks Martin! 
And it is really kate at fault, as you could "freeze" your whole menu if you have two text files open under recent documents and try to open them both from the menu.

**Comment by star-buck** [comment]
any solution or temporary fix to this?

**Comment by mck182** [comment]
One temporary workaround I found is removing "X-DBUS-StartupType=Multi" from org.kde.kate.desktop file.

I'm unsure if this have any side effects on Kate though, but I've been using it over the weekend and seemed fine as far as I can tell.

**Comment by mck182** [comment]
This should be more of a proper fix: https://git.reviewboard.kde.org/r/122498/

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4768461/+listing-archive-extra

**Comment by star-buck** [comment]
seems to work, awesome!
