### ISSUE TITLE
[kmixer]: output volume from device and application "interlocked"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#67]
https://www.dropbox.com/s/y1ahwd666i3e57o/kmixer-locked.mkv?dl=0
Is there a trick or setting to have master volume output and apps output non-interlocked?

**Comment by apachelogger** [comment]
this looks more like the pulseaudio that is installed employs a feature called flat volumes where *increasing* the volume of any application beyond the volume of the 'master' it would also increase the volume of the master. This in turn means that 100% always means 100% of what is possible hardware wise, traditionally of course it would be 100% of whatever master is. Whether or not that makes sense, it's the pulseaudio default. So this sounds an awful lot like a bug in the pulseaudio backport.

@jriddell I think this might be a pulseaudio backport bug :scream:

**Comment by apachelogger** [comment]
found the problem

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4703404/+listing-archive-extra

**Comment by star-buck** [comment]
seems fixed
