### ISSUE TITLE
[radiotray]: icons all "white pages"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#69]

**Comment by davidedmundson** [comment]
https://git.reviewboard.kde.org/r/122384/diff/#

This fixes the icon in the systray; there's still one missing in the menu; but that seems to be a different problem. Investigating that now

**Comment by davidedmundson** [comment]
Pushed into plasma-workspace 7b9156406bfd7ab51bcac984d3aa2ffd3b848284

The menu icons were missing because the icon name is explicitly gtk-quit and gtk-preferences; so it needs a gnome icon theme installed. 
Not a lot we can do about that, without changing GTK to stop being so ridiculous.

**Comment by star-buck** [comment]
is it enough to have the default "gnome iconset" installed and set gtk+ look under systemsettings to "Oxygen" with Fallback "Gnome"?

**Comment by apachelogger** [comment]
https://launchpad.net/~netrunner-os/+archive/ubuntu/netrunner-15-ci-fixes/+sourcepub/4751191/+listing-archive-extra

**Comment by davidedmundson** [comment]
>is it enough to have the default "gnome iconset" installed and set gtk+ look under systemsettings to "Oxygen" with Fallback "Gnome"?

No. That's the problem :(

In Plasma 4 the app (radiotray) drew all the menu itself, embedding it via xembed.

Now it's providid the main icon name and menu items (text+icon names) as text over dbus and then plasma does the rendering.

Which means Plasma is what needs to fall back into an icon set with these gtk specificly named icons.

**Comment by star-buck** [comment]
seems fixed.
